In [1]:
import numpy as np
array1=np.array([])
print(array1)

[]


In [3]:
array2=np.empty(shape=(3,3))
print(array2)

[[4.67296746e-307 1.69121096e-306 1.29060871e-306]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]


In [8]:
import random
value=random.random()
print(value)

0.01077652741478441


In [7]:
import random
v=random.uniform(3,7)
print(v)

3.5663495605256625


In [6]:
import random
v2=random.randint(1,6)
print(v2)

3


In [10]:
print(sum(range(1,102)))

5151


In [14]:
num=2344
p = int(str(num)[::-1])  # Convert to string, reverse, then convert back to integer
print(p)


4432


In [15]:
num=7896
rev=0
while num>0:
    digit=num%10
    rev=rev*10+digit
    num=num//10
print(rev)

6987
